version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/ancientbowling
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - springboot-mysql-network
  mysqldb:
    image: mysql:8.0.34
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=ancientbowling
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      - springboot-mysql-network
volumes:
  mysql-data:
networks:
  springboot-mysql-network:
    name: springboot-mysql-network